services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    platform: linux/amd64
    ports:
      - "5432:5432"
    hostname: postgres
    restart: always
    command: -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sampledb
      TZ: "Asia/Tokyo"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
